package vm

var handler map[opcode]operation = map[opcode]operation{
	ADD: add_op{},
	SUB: sub_op{},
	MUL: mul_op{},
	DIV: div_op{},
	INC: inc_op{},
	DEC: dec_op{},
	MOV: mov_op{},
	LOD: lod_op{},
	STR: str_op{},
	HLT: hlt_op{},
	NOP: nop_op{},
	PRT: prt_op{},
	JMP: jmp_op{},
	JIF: jif_op{},
	JID: jid_op{},
	JIZ: jiz_op{},
	JIE: jie_op{},
	JNE: jne_op{},
	JIG: jig_op{},
	JIS: jis_op{},
	JEG: jeg_op{},
	JES: jes_op{},
}
